version: '3.8'

services:
  postgres_db:
    image: postgis/postgis:16-3.4
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-campus_navigation}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pg_data_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-campus_navigation}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  pg_data_volume: 